using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace G4Composer.Server.Data.Migrations
{
    /// <inheritdoc />
    public partial class FixPdbCacheIdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 20260805110000_AddPdbCache only annotated Id with "Sqlite:Autoincrement" — no
            // Npgsql identity-generation annotation — so on Postgres the columns landed as
            // plain "integer" with no sequence/default. EF still treats Id as
            // ValueGeneratedOnAdd and sends NULL on insert, which Postgres rejects
            // (23502: null value in column "Id" violates not-null constraint). Tables were
            // still empty in production when this was found, so no data migration is needed,
            // just adding identity generation to the existing PK columns.
            //
            // SQLite has no such gap — INTEGER PRIMARY KEY is always rowid-aliased and
            // autoincrements regardless of this annotation. Postgres-only fix.
            if (!migrationBuilder.IsNpgsql()) return;

            migrationBuilder.Sql(@"ALTER TABLE ""PdbCacheEntries"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
            migrationBuilder.Sql(@"ALTER TABLE ""PdbCacheFrames"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (!migrationBuilder.IsNpgsql()) return;

            migrationBuilder.Sql(@"ALTER TABLE ""PdbCacheFrames"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql(@"ALTER TABLE ""PdbCacheEntries"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
        }
    }
}
