// <auto-generated />
using G4Composer.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G4Composer.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621120000_Fix6r9lChi")]
    partial class Fix6r9lChi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("G4Composer.Server.Data.Entities.SilvaGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Groove")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SilvaGroups");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.SilvaSubtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Loop")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Onz")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Silva")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SilvaGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SilvaGroupId");

                    b.ToTable("SilvaSubtypes");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.StructureExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chi")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("InpName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTheoretical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Orient")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdbId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rise")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RmLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SilvaSubtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tetrads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Twist")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PdbId")
                        .IsUnique();

                    b.HasIndex("SilvaSubtypeId");

                    b.ToTable("StructureExamples");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.SilvaSubtype", b =>
                {
                    b.HasOne("G4Composer.Server.Data.Entities.SilvaGroup", "Group")
                        .WithMany("Subtypes")
                        .HasForeignKey("SilvaGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.StructureExample", b =>
                {
                    b.HasOne("G4Composer.Server.Data.Entities.SilvaSubtype", "Subtype")
                        .WithMany("Examples")
                        .HasForeignKey("SilvaSubtypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subtype");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.SilvaGroup", b =>
                {
                    b.Navigation("Subtypes");
                });

            modelBuilder.Entity("G4Composer.Server.Data.Entities.SilvaSubtype", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
